#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] Pre-commit"
echo "[Husky] Running Eslint"
npm run lint

echo "[Husky] Running Prettier"
npm run prettier

echo "[Husky] Running openapi validator"
npm run lint:openapi

echo "[Husky] Building project"
npm run build

echo "[Husky] Deleting dist folder"
rm -rf dist